In [3]:
!pip install pulp

     |████████████████████████████████| 41.2 MB 78 kB/s 


In [4]:
import numpy as np
import pandas as pd
import pulp

In [153]:
c_prib = [3, 1, 3, 2, 3]
c_val_ob = [10, 9, 12, 14, 9]
c_sebes = [7, 8, 9, 12, 6]
c_ur_nag = [7, 10, 17, 10, 12]

In [154]:
cons_res = [[4,5,3,2,3],
            [2,4,4,4,2],
            [3,1,0,1,1]]
b_res = [3000,4500,1500]

cons_fond = [[2,3,5,4,5],
             [1,2,6,3,2],
             [3,4,4,1,4],
             [1,1,2,2,1]]
b_fond = [5000,4000,4000,2000]

ust = 0.15


In [155]:
variables = []
for k in range(1, 6):
    variables.append(pulp.LpVariable(f'x{k}', 100, 500, pulp.LpInteger))

In [162]:
LP1 = pulp.LpProblem('Прибыль', pulp.LpMaximize)
LP1 += pulp.lpSum([coef*var for coef, var in zip(c_prib, variables)]), "Прибыль"

for cons, b in zip(cons_res, b_res):
    LP1+= pulp.lpSum([coef*var for coef, var in zip(cons, variables)]) <= b

for cons, b in zip(cons_fond, b_fond):
    LP1+= pulp.lpSum([coef*var for coef, var in zip(cons, variables)]) <= b


LP1 += pulp.lpSum([coef*var for coef, var in zip(c_ur_nag, variables)]) <= 15000
LP1 += pulp.lpSum([coef*var for coef, var in zip(c_val_ob, variables)]) >= 12000
LP1 += pulp.lpSum([coef*var for coef, var in zip(c_sebes, variables)]) <= 10000

In [163]:
LP1

Прибыль:
MAXIMIZE
3*x1 + 1*x2 + 3*x3 + 2*x4 + 3*x5 + 0
SUBJECT TO
_C1: 4 x1 + 5 x2 + 3 x3 + 2 x4 + 3 x5 <= 3000

_C2: 2 x1 + 4 x2 + 4 x3 + 4 x4 + 2 x5 <= 4500

_C3: 3 x1 + x2 + x4 + x5 <= 1500

_C4: 2 x1 + 3 x2 + 5 x3 + 4 x4 + 5 x5 <= 5000

_C5: x1 + 2 x2 + 6 x3 + 3 x4 + 2 x5 <= 4000

_C6: 3 x1 + 4 x2 + 4 x3 + x4 + 4 x5 <= 4000

_C7: x1 + x2 + 2 x3 + 2 x4 + x5 <= 2000

_C8: 7 x1 + 10 x2 + 17 x3 + 10 x4 + 12 x5 <= 15000

_C9: 10 x1 + 9 x2 + 12 x3 + 14 x4 + 9 x5 >= 12000

_C10: 7 x1 + 8 x2 + 9 x3 + 12 x4 + 6 x5 <= 10000

VARIABLES
100 <= x1 <= 500 Integer
100 <= x2 <= 500 Integer
100 <= x3 <= 500 Integer
100 <= x4 <= 500 Integer
100 <= x5 <= 500 Integer

In [166]:
s1 = LP1.solve()
V = np.array([])
for v in LP1.variables():
    V = np.append(V, v.varValue)
print('x = ', V)
prib_opt = sum([a*b for a,b in zip(c_prib, V)])

print('Прибыль:',sum([a*b for a,b in zip(c_prib, V)]))
print('Валовый объем', sum([a*b for a,b in zip(c_val_ob, V)]))
print('Себестоимость',sum([a*b for a,b in zip(c_sebes, V)]))
print('Уровень нагрузки',sum([a*b for a,b in zip(c_ur_nag, V)]))

x =  [100. 100. 100. 498. 268.]
Прибыль: 2500.0
Валовый объем 12484.0
Себестоимость 9984.0
Уровень нагрузки 11596.0


# Прибыль

In [134]:
LP1 = pulp.LpProblem('Прибыль', pulp.LpMaximize)
LP1 += pulp.lpSum([coef*var for coef, var in zip(c_prib, variables)]), "Прибыль"

for cons, b in zip(cons_res, b_res):
    LP1+= pulp.lpSum([coef*var for coef, var in zip(cons, variables)]) <= b

for cons, b in zip(cons_fond, b_fond):
    LP1+= pulp.lpSum([coef*var for coef, var in zip(cons, variables)]) <= b

In [135]:
LP1

Прибыль:
MAXIMIZE
3*x1 + 1*x2 + 3*x3 + 2*x4 + 3*x5 + 0
SUBJECT TO
_C1: 4 x1 + 5 x2 + 3 x3 + 2 x4 + 3 x5 <= 3000

_C2: 2 x1 + 4 x2 + 4 x3 + 4 x4 + 2 x5 <= 4500

_C3: 3 x1 + x2 + x4 + x5 <= 1500

_C4: 2 x1 + 3 x2 + 5 x3 + 4 x4 + 5 x5 <= 5000

_C5: x1 + 2 x2 + 6 x3 + 3 x4 + 2 x5 <= 4000

_C6: 3 x1 + 4 x2 + 4 x3 + x4 + 4 x5 <= 4000

_C7: x1 + x2 + 2 x3 + 2 x4 + x5 <= 2000

VARIABLES
100 <= x1 <= 500 Integer
100 <= x2 <= 500 Integer
100 <= x3 <= 500 Integer
100 <= x4 <= 500 Integer
100 <= x5 <= 500 Integer

In [136]:
s1 = LP1.solve()
V = np.array([])
for v in LP1.variables():
    V = np.append(V, v.varValue)
print('x = ', V)
prib_opt = sum([a*b for a,b in zip(c_prib, V)])
print(prib_opt)

x =  [100. 100. 100. 498. 268.]
2500.0


In [83]:
pulp.LpStatus[LP1.status]

'Optimal'

# Валовый объем

In [84]:
LP2 = pulp.LpProblem('Валовый_объем', pulp.LpMaximize)
LP2 += pulp.lpSum([coef*var for coef, var in zip(c_val_ob, variables)]), "Объем"
for cons, b in zip(cons_res, b_res):
    LP2+= pulp.lpSum([coef*var for coef, var in zip(cons, variables)]) <= b

for cons, b in zip(cons_fond, b_fond):
    LP2+= pulp.lpSum([coef*var for coef, var in zip(cons, variables)]) <= b

In [85]:
LP2 += pulp.lpSum([coef*var for coef, var in zip(c_prib, variables)]) >= prib_opt-(prib_opt*ust)

In [137]:
LP2

Валовый_объем:
MAXIMIZE
10*x1 + 9*x2 + 12*x3 + 14*x4 + 9*x5 + 0
SUBJECT TO
_C1: 4 x1 + 5 x2 + 3 x3 + 2 x4 + 3 x5 <= 3000

_C2: 2 x1 + 4 x2 + 4 x3 + 4 x4 + 2 x5 <= 4500

_C3: 3 x1 + x2 + x4 + x5 <= 1500

_C4: 2 x1 + 3 x2 + 5 x3 + 4 x4 + 5 x5 <= 5000

_C5: x1 + 2 x2 + 6 x3 + 3 x4 + 2 x5 <= 4000

_C6: 3 x1 + 4 x2 + 4 x3 + x4 + 4 x5 <= 4000

_C7: x1 + x2 + 2 x3 + 2 x4 + x5 <= 2000

_C8: 3 x1 + x2 + 3 x3 + 2 x4 + 3 x5 >= 2250

VARIABLES
100 <= x1 <= 500 Integer
100 <= x2 <= 500 Integer
100 <= x3 <= 500 Integer
100 <= x4 <= 500 Integer
100 <= x5 <= 500 Integer

In [138]:
s2 = LP2.solve()
V = np.array([])
for v in LP2.variables():
    V = np.append(V, v.varValue)
print(V)
val_ob_opt = sum([a*b for a,b in zip(c_val_ob, V)])
print(val_ob_opt)

[100. 100. 266. 500. 100.]
12992.0


# Себестоимость

In [142]:
LP3 = pulp.LpProblem('Себестоимость', pulp.LpMinimize)
LP3 += pulp.lpSum([coef*var for coef, var in zip(c_sebes, variables)]), "Себестоимость"
for cons, b in zip(cons_res, b_res):
    LP3+= pulp.lpSum([coef*var for coef, var in zip(cons, variables)]) <= b

for cons, b in zip(cons_fond, b_fond):
    LP3+= pulp.lpSum([coef*var for coef, var in zip(cons, variables)]) <= b

In [143]:
LP3 += pulp.lpSum([coef*var for coef, var in zip(c_prib, variables)]) >= prib_opt-(prib_opt*ust)
LP3 += pulp.lpSum([coef*var for coef, var in zip(c_val_ob, variables)]) >= val_ob_opt-int((val_ob_opt*ust))

In [144]:
LP3

Себестоимость:
MINIMIZE
7*x1 + 8*x2 + 9*x3 + 12*x4 + 6*x5 + 0
SUBJECT TO
_C1: 4 x1 + 5 x2 + 3 x3 + 2 x4 + 3 x5 <= 3000

_C2: 2 x1 + 4 x2 + 4 x3 + 4 x4 + 2 x5 <= 4500

_C3: 3 x1 + x2 + x4 + x5 <= 1500

_C4: 2 x1 + 3 x2 + 5 x3 + 4 x4 + 5 x5 <= 5000

_C5: x1 + 2 x2 + 6 x3 + 3 x4 + 2 x5 <= 4000

_C6: 3 x1 + 4 x2 + 4 x3 + x4 + 4 x5 <= 4000

_C7: x1 + x2 + 2 x3 + 2 x4 + x5 <= 2000

_C8: 3 x1 + x2 + 3 x3 + 2 x4 + 3 x5 >= 2125

_C9: 10 x1 + 9 x2 + 12 x3 + 14 x4 + 9 x5 >= 11044

VARIABLES
100 <= x1 <= 500 Integer
100 <= x2 <= 500 Integer
100 <= x3 <= 500 Integer
100 <= x4 <= 500 Integer
100 <= x5 <= 500 Integer

In [145]:
s3 = LP3.solve()
V = np.array([])
for v in LP3.variables():
    V = np.append(V, v.varValue)
print(V)
sebes_opt = sum([a*b for a,b in zip(c_sebes, V)])
print(sebes_opt)
print(sum([a*b for a,b in zip(c_prib, V)]))
print(sum([a*b for a,b in zip(c_val_ob, V)]))

[100. 100. 100. 318. 388.]
8544.0
2500.0
11044.0


# Загрузка оборудования

In [146]:
LP4 = pulp.LpProblem('Загрузка', pulp.LpMinimize)
LP4 += pulp.lpSum([coef*var for coef, var in zip(c_ur_nag, variables)]), "Загрузка"
for cons, b in zip(cons_res, b_res):
    LP4+= pulp.lpSum([coef*var for coef, var in zip(cons, variables)]) <= b

for cons, b in zip(cons_fond, b_fond):
    LP4+= pulp.lpSum([coef*var for coef, var in zip(cons, variables)]) <= b

In [147]:
LP4 += pulp.lpSum([coef*var for coef, var in zip(c_prib, variables)]) >= prib_opt-int((prib_opt*ust))
LP4 += pulp.lpSum([coef*var for coef, var in zip(c_val_ob, variables)]) >= val_ob_opt-int((val_ob_opt*ust))
LP4 += pulp.lpSum([coef*var for coef, var in zip(c_sebes, variables)]) <= sebes_opt+int((sebes_opt*ust))

In [148]:
LP4

Загрузка:
MINIMIZE
7*x1 + 10*x2 + 17*x3 + 10*x4 + 12*x5 + 0
SUBJECT TO
_C1: 4 x1 + 5 x2 + 3 x3 + 2 x4 + 3 x5 <= 3000

_C2: 2 x1 + 4 x2 + 4 x3 + 4 x4 + 2 x5 <= 4500

_C3: 3 x1 + x2 + x4 + x5 <= 1500

_C4: 2 x1 + 3 x2 + 5 x3 + 4 x4 + 5 x5 <= 5000

_C5: x1 + 2 x2 + 6 x3 + 3 x4 + 2 x5 <= 4000

_C6: 3 x1 + 4 x2 + 4 x3 + x4 + 4 x5 <= 4000

_C7: x1 + x2 + 2 x3 + 2 x4 + x5 <= 2000

_C8: 3 x1 + x2 + 3 x3 + 2 x4 + 3 x5 >= 2125

_C9: 10 x1 + 9 x2 + 12 x3 + 14 x4 + 9 x5 >= 11044

_C10: 7 x1 + 8 x2 + 9 x3 + 12 x4 + 6 x5 <= 9825

VARIABLES
100 <= x1 <= 500 Integer
100 <= x2 <= 500 Integer
100 <= x3 <= 500 Integer
100 <= x4 <= 500 Integer
100 <= x5 <= 500 Integer

In [149]:
LP4 += pulp.lpSum([coef*var for coef, var in zip([1,0,0,0,0], variables)]) >= 100

In [152]:
s4 = LP4.solve()
V = np.array([])
for v in LP4.variables():
    V = np.append(V, v.varValue)
print(V)
ur_nag_opt = sum([a*b for a,b in zip(c_ur_nag, V)])
print('Прибыль:',sum([a*b for a,b in zip(c_prib, V)]))
print('Валовый объем', sum([a*b for a,b in zip(c_val_ob, V)]))
print('Себестоимость',sum([a*b for a,b in zip(c_sebes, V)]))
print('Уровень нагрузки',ur_nag_opt)

[292. 100. 100. 366. 100.]
Прибыль: 2308.0
Валовый объем 11044.0
Себестоимость 8736.0
Уровень нагрузки 9604.0
